name: Build Orologic per Windows e macOS

on:
  workflow_dispatch:

jobs:
  # --- PRIMO LAVORO: COMPILAZIONE PER WINDOWS ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get site-packages path
        # AGGIUNTO: Trova il percorso di site-packages e lo salva in una variabile d'ambiente
        id: get-site-packages
        run: |
          $site_packages = python -c "import site; print(site.getsitepackages()[0])"
          echo "SITE_PACKAGES=$site_packages" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - name: Run PyInstaller
        # MODIFICATO: Aggiunta l'opzione --paths per usare la variabile
        run: pyinstaller --name Orologic.exe --onefile --add-data "readme.htm;." --add-data "eco.db;." --hidden-import GBUtils --paths "$env:SITE_PACKAGES" orologic.py
        shell: pwsh
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-Windows
          path: dist/Orologic.exe

  # --- SECONDO LAVORO: COMPILAZIONE PER MACOS ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get site-packages path
        # AGGIUNTO: Trova il percorso di site-packages e lo salva in una variabile d'ambiente
        id: get-site-packages-macos
        run: echo "SITE_PACKAGES=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
      - name: Run PyInstaller for Console App
        # MODIFICATO: Aggiunta l'opzione --paths per usare la variabile
        run: pyinstaller --name Orologic --onefile --target-arch universal2 --add-data "readme.htm:." --add-data "eco.db:." --hidden-import GBUtils --paths "$SITE_PACKAGES" orologic.py
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-macOS-Universal
          path: dist/Orologic