name: Build Orologic per Windows e macOS

on:
  workflow_dispatch:

jobs:
  # --- PRIMO LAVORO: COMPILAZIONE PER WINDOWS ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        # MODIFICA FINALE: Usiamo --collect-all per forzare l'inclusione di tutto il pacchetto scipy
        run: pyinstaller --name Orologic.exe --onefile --add-data "readme.htm;." --add-data "eco.db;." --hidden-import GBUtils --collect-all scipy orologic.py
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-Windows
          path: dist/Orologic.exe

  # --- SECONDO LAVORO: COMPILAZIONE PER MACOS ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller for Console App
        # MODIFICA FINALE: Usiamo --collect-all per forzare l'inclusione di tutto il pacchetto scipy
        run: pyinstaller --name Orologic --onefile --target-arch universal2 --add-data "readme.htm:." --add-data "eco.db:." --hidden-import GBUtils --collect-all scipy orologic.py
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-macOS-Universal
          path: dist/Orologic