# Nome del tuo processo, apparirà nella scheda "Actions" di GitHub
name: Build Orologic per Windows e macOS

# Quando deve partire questo processo? 
# In questo caso, ogni volta che carichi (push) nuovo codice sul tuo branch 'main'
on:
  workflow_dispatch:
    branches: [ "main" ]

# Qui definiamo i "lavori" da fare. Ne abbiamo due: uno per Windows e uno per macOS.
jobs:
  # --- PRIMO LAVORO: COMPILAZIONE PER WINDOWS (CORRETTO) ---
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Comando corretto: --windowed rimosso e separatore ; usato per --add-data
      - name: Run PyInstaller
        run: pyinstaller --name Orologic --onefile --add-data "readme.htm;." --add-data "eco.db;." orologic.py
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-Windows
          path: dist/Orologic.exe

  # --- SECONDO LAVORO: COMPILAZIONE PER MACOS (GIÀ CORRETTO) ---
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Questo comando era già corretto (senza --windowed e con : come separatore)
      - name: Run PyInstaller
        run: pyinstaller --name Orologic --onefile --add-data "readme.htm:." --add-data "eco.db:." orologic.py
      - name: Zip .app file
        run: ditto -c -k --sequesterRsrc --keepParent dist/Orologic.app Orologic-macOS.zip
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orologic-macOS
          path: Orologic-macOS.zip